name: Unit Test Checks
on: pull_request

jobs:
  tests:
    name: runner / pytest unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - run: uv sync --all-extras --dev
      - run: uv run pytest .
